export const homeObjOne = {
    id:'about',
    lightBg:false,
    lightText:true,
    lightTextDesc:true,
    topLine:'Premium Bank',
    headLine:'Adipisicing duis excepteur elit cupidat',
    description:'Consequat ut non in qui. Esse ea aliqua quis minim sint pariatur. Et laboris deserunt ut sint. Occaecat enim exercitation id veniam laboris excepteur.',
    buttonLabel:'Get Started',
    imgStart:false,
    img:require('../../images/svg-5.svg'),
    alt:'Car',
    dark:true,
    primary:true,
    darkText:false,
}

export const homeObjTwo = {
    id:'discover',
    lightBg:true,
    lightText:false,
    lightTextDesc:true,
    topLine:'Unlimited Acces',
    headLine:'Adipisicing duis excepteur elit cupidat',
    description:'Consequat ut non in qui. Esse ea aliqua quis minim sint pariatur. Et laboris deserunt ut sint. Occaecat enim exercitation id veniam laboris excepteur.',
    buttonLabel:'Learn More',
    imgStart:false,
    img:require('../../images/svg-1.svg'),
    alt:'Car',
    dark:false,
    primary:false,
    darkText:true,
}

export const homeObjThree = {
    id:'signup',
    lightBg:false,
    lightText:true,
    lightTextDesc:true,
    topLine:'SignUp',
    headLine:'Adipisicing at',
    description:'Consequat ut non in quariatur. Et laboris deserunt ut sint. Occaecat enim exercitation id veniam laboris excepteur.',
    buttonLabel:'Sign Up',
    imgStart:true,
    img:require('../../images/svg-2.svg'),
    alt:'Car',
    dark:true,
    primary:true,
    darkText:false,
}